name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "nownews_DB"
database_id = "c023a361-7dad-4186-aba2-cfad93f59f46"
